.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH vimdoc-language-server-check 1  "check 0.2.1"
.SH NAME
vimdoc\-language\-server\-check \- Check vimdoc files for diagnostics
.SH SYNOPSIS
\fBvimdoc\-language\-server check\fR [\fB\-\-ignore\fR] [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-\-log\-file\fR] [\fB\-\-line\-width\fR] [\fB\-\-tag\-path\fR] [\fB\-\-runtime\-tags\fR] [\fB\-\-no\-runtime\-tags\fR] [\fB\-\-color\fR] [\fB\-\-no\-color\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIPATH\fR>
.SH DESCRIPTION
Check vimdoc files for diagnostics
.SH OPTIONS
.TP
\fB\-\-ignore\fR \fI<CODE>\fR
Ignore a diagnostic code
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase logging verbosity; repeat for more detail
.TP
\fB\-\-log\-file\fR \fI<PATH>\fR
Write logs to PATH instead of stderr
.TP
\fB\-\-line\-width\fR \fI<N>\fR [default: 78]
Target line width for vimdoc formatting
.TP
\fB\-\-tag\-path\fR \fI<PATH>\fR
Load additional Vim tags from PATH
.TP
\fB\-\-runtime\-tags\fR
Load tags from the discovered Vim runtime
.TP
\fB\-\-no\-runtime\-tags\fR
Do not load tags from the discovered Vim runtime
.TP
\fB\-\-color\fR
Always use colored CLI output
.TP
\fB\-\-no\-color\fR
Never use colored CLI output
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fIPATH\fR>
Directory containing vimdoc files
.SH VERSION
v0.2.1
