name: format

on:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix develop .#ci --command just format
